[package]
name = "poms-compute"
version = "0.1.0"
edition = "2021"

[dependencies]
poms-common = { path = "../poms-common" }
bytemuck = { version = "1.8", features = ["derive", "extern_crate_alloc"] }
wgpu = "0.19"
