[workspace]
resolver = "2"

members = [
    "src/poms-app",
    "src/poms-common",
    "src/poms-compute",
    "src/poms-render",
]


[workspace.dependencies]
bytemuck = { version = "1.8", features = ["derive", "extern_crate_alloc"] }
cgmath = "0.18"
wgpu = "0.20"
