[package]
name = "visitlab-wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.26"
cgmath = "0.18"
simple_logger = "2.1"
wgpu = "0.12"
bytemuck = { version = "1.8", features = ["derive", "extern_crate_alloc"] }
futures = "0.3"
reqwest-wasm = "0.11"
log = "0.4"

[target.wasm32-unknown-unknown.dependencies]
console_error_panic_hook = "0.1"
web-sys = "0.3"
wasm-logger = "0.2.0"
wasm-bindgen-futures = "0.4"

[patch.crates-io]
# New shader syntax required by Chrome Canary has not been officially released.
# Patch wgpu dependency to use the latest version of the shader compiler.
wgpu = { git = "https://github.com/gfx-rs/wgpu", rev = "58f318550dedaec6ed901c83131e424cf39ee648" }

[features]
legacy-shader = []
