[package]
name = "visitlab-wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.27", features = ["x11"] }
cgmath = "0.18"
simple_logger = "2.1"
wgpu = "0.13"
bytemuck = { version = "1.8", features = ["derive", "extern_crate_alloc"] }
futures = "0.3"
log = "0.4"

epi = "0.17"
egui = { version = "0.19", default-features = false }
egui-winit = { version = "0.19", default-features = false }
egui_wgpu_backend = "0.19"
egui_winit_platform = "0.16"
egui_demo_lib = "0.19"
rfd = "0.10"
instant = "0.1"

[target.wasm32-unknown-unknown.dependencies]
getrandom = { version = "0.2", features = ["js"] }
console_error_panic_hook = "0.1"
web-sys = { version = "0.3", features = ["Window", "Response"] }
wasm-logger = "0.2.0"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
