pub const MIN_DISTANCE_FIELD_RESOLUTION: u32 = 64;
pub const MAX_DISTANCE_FIELD_RESOLUTION: u32 = 256;
pub const MAX_NUM_GRID_POINTS: usize = u32::pow(MAX_DISTANCE_FIELD_RESOLUTION, 3) as usize;

pub const MIN_PROBE_RADIUS: f32 = 1.4;
pub const MAX_PROBE_RADIUS: f32 = 10.0;

pub const MAX_NUM_ATOMS: usize = 1_000_000;

pub const MIN_ANIMATION_SPEED: u32 = 1;
pub const MAX_ANIMATION_SPEED: u32 = 10;
