[package]
name = "poms-render"
version = "0.1.0"
edition = "2021"

[dependencies]
poms-common = { path = "../poms-common" }

bytemuck = { workspace = true }
cgmath = { workspace = true }
wgpu = { workspace = true }
