[package]
name = "compute"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
bytemuck = { version = "1.8", features = ["derive", "extern_crate_alloc"] }
wgpu = "0.19"
